// Code generated by mockery v2.20.0. DO NOT EDIT.

package productbiz

import (
	context "context"

	productmodel "github.com/hvchien216/golang-ecommerce/internal/modules/product/productmodel"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateProductStore is an autogenerated mock type for the CreateProductStore type
type MockCreateProductStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockCreateProductStore) Create(ctx context.Context, data *productmodel.Product) (*productmodel.Product, error) {
	ret := _m.Called(ctx, data)

	var r0 *productmodel.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productmodel.Product) (*productmodel.Product, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productmodel.Product) *productmodel.Product); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productmodel.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productmodel.Product) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockCreateProductStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockCreateProductStore creates a new instance of MockCreateProductStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockCreateProductStore(t mockConstructorTestingTNewMockCreateProductStore) *MockCreateProductStore {
	mock := &MockCreateProductStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
