// Code generated by mockery v2.20.0. DO NOT EDIT.

package categorybiz

import (
	common "github.com/hvchien216/golang-ecommerce/common"
	categorymodel "github.com/hvchien216/golang-ecommerce/internal/modules/category/categorymodel"

	context "context"

	mock "github.com/stretchr/testify/mock"

	orm "github.com/hvchien216/golang-ecommerce/internal/orm"
)

// MockBusiness is an autogenerated mock type for the Business type
type MockBusiness struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, input
func (_m *MockBusiness) CreateCategory(ctx context.Context, input categorymodel.NewCategoryInput) (*orm.Category, error) {
	ret := _m.Called(ctx, input)

	var r0 *orm.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, categorymodel.NewCategoryInput) (*orm.Category, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, categorymodel.NewCategoryInput) *orm.Category); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orm.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, categorymodel.NewCategoryInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindCategory provides a mock function with given fields: ctx, id
func (_m *MockBusiness) FindCategory(ctx context.Context, id int) (*orm.Category, error) {
	ret := _m.Called(ctx, id)

	var r0 *orm.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*orm.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *orm.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orm.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCategory provides a mock function with given fields: ctx, filter, paging
func (_m *MockBusiness) ListCategory(ctx context.Context, filter *categorymodel.Filter, paging *common.Paging) ([]*orm.Category, int64, error) {
	ret := _m.Called(ctx, filter, paging)

	var r0 []*orm.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *categorymodel.Filter, *common.Paging) ([]*orm.Category, int64, error)); ok {
		return rf(ctx, filter, paging)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *categorymodel.Filter, *common.Paging) []*orm.Category); ok {
		r0 = rf(ctx, filter, paging)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*orm.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *categorymodel.Filter, *common.Paging) int64); ok {
		r1 = rf(ctx, filter, paging)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *categorymodel.Filter, *common.Paging) error); ok {
		r2 = rf(ctx, filter, paging)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateCategory provides a mock function with given fields: ctx, id, name, description, parentID
func (_m *MockBusiness) UpdateCategory(ctx context.Context, id int, name string, description *string, parentID *int) (*orm.Category, error) {
	ret := _m.Called(ctx, id, name, description, parentID)

	var r0 *orm.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, *string, *int) (*orm.Category, error)); ok {
		return rf(ctx, id, name, description, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, *string, *int) *orm.Category); ok {
		r0 = rf(ctx, id, name, description, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orm.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, *string, *int) error); ok {
		r1 = rf(ctx, id, name, description, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockBusiness interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockBusiness creates a new instance of MockBusiness. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockBusiness(t mockConstructorTestingTNewMockBusiness) *MockBusiness {
	mock := &MockBusiness{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
